project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!/docs/scripts/*.qmd"

website:
  title: "PS405 Linear Models"
  navbar:
    left:
      - text: " "
        href: index.qmd
        

format:
  html:
    theme:
      light: [flatly, custom.scss]
    mainfont: roboto
    css: styles.css
    toc: true



