---
title: ""
format: 
  html:
    toc: false
listing:
  - id: schedule
    include: 
      type: "schedule"
    contents: classes.yaml
    type: table
    fields: [Week, title, Link, Code, Data]
    filter-ui: false
    sort: "week"
    sort-ui: false
---

## Description

This site is designed to support students enrolled in the PS405 Linear Models course. Here, you will find lab materials, which are also available on Canvas. In the section, we will focus on coding and practicing the concepts covered in the lectures.

:::: {.columns}

::: {.column}
### Section Details

- {{< fa calendar >}} &nbsp; Thursday
- {{< fa clock >}} &nbsp; 11:00 AM -- 11:50 AM
- {{< fa location-dot >}} &nbsp; Scott Hall 212

:::

::: {.column}
### Office Hours Details

- {{< fa calendar >}} &nbsp; Tuesday
- {{< fa clock >}} &nbsp; 11:00 AM -- 12:30 PM
- {{< fa location-dot >}} &nbsp; Scott Hall 110
:::

::::

## Schedule

:::{#schedule}
:::

## Pset Grade Increase Policy

To improve your grade for the problem set, you should submit the exercises from the corresponding lab session held during the week the homework was assigned. Exercises can be found at the end of each lab. You can increase grades for every problem set, except for the last one before the final. The maximum possible increase is two points.

For instance, if you wish to improve the grade for the first homework, which was assigned on January 16th, you should submit the completed exercises from the second lab, which took place on the same day. If you prefer not to check the dates each time, given that homework is assigned each week starting from week 2, you can use the formula: 

$$
\text{Lab Number}|\text{Pset is assigned each week} = \text{Pset Number} + 1
$$

After the grades are released, you have one week to submit the `.qmd` file via email to artur.baranov@u.northwestern.edu. 

## Additional Resources

### Helpful Regression Resources

- [Step-by-step regression guide](https://evalsp24.classes.andrewheiss.com/example/regression.html)

### Data sources

-   [Political Science datasets](https://github.com/erikgahner/PolData)

### Visualization

-   [Introduction to ggplot2](https://jrnold.github.io/r4ds-exercise-solutions/data-visualisation.html)

-   [Maps/Networks/Advanced vizualisation with ggplot2](https://ggplot2-book.org)

-   [Making interactive plots with ggplot2](https://plotly.com/ggplot2/box-plots/)
